urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^$', 'gradecalc.views.index_view', name='index'),
)

models.py
from django.db import models

class Course(models.Model):
    name = models.CharField(max_length=200)
    department = models.CharField(max_length=200)
    number = models.CharField(max_length=200)
    section = models.CharField(max_length=50)
    instructors = models.CharField(max_length=200)

    class Meta:
        abstract = True

    def course_id(self):
        return self.department + self.number


class PointsCourse(Course):
    points = models.PositiveIntegerField()


class PercentCourse(Course):
    pass


class Group(models.Model):
    name = models.CharField(max_length=200)
    percent = models.PositiveIntegerField()
    course = models.ForeignKey(PercentCourse)


class Assignment(models.Model):
    name = models.CharField(max_length=200)

    class Meta:
        abstract = True


class PointsAssignment(Assignment):
    group = models.ForeignKey(PointsCourse)
    points = models.PositiveIntegerField()


class PercentAssignment(Assignment):
    group = models.ForeignKey(Group)

views.py
from django.shortcuts import render
from gradecalc.models import PointsCourse, PercentCourse

def index_view(request):
    courses = list(PointsCourse.objects.all()) + list(PercentCourse.objects.all())
    return render(request, 'gradecalc/index.html', {'courses': courses})

templates/gradecalc/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en-US">
<head>
  <!-- stylesheets -->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" />
  <link rel="stylesheet" href="https://bootflat.github.io/bootflat/css/bootflat.css" />
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" />
  <link href="{% static 'gradecalc/stylesheets/screen.css' %}" rel="stylesheet" />
  <!-- jQuery -->
  {% block extra_includes %}{% endblock %}
  <script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="https://code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
  <title>{% block title %}Grade Calculator{% endblock %}</title>
</head>
<body>
  <div id="main">
    <nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    {% block header %}
      <div class="container-fluid col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
             <li><a data-toggle="modal" data-target="#logoutModal" data-placement="bottom" data-toggle="tooltip" type="button" data-original-title="log out" id="tooltip">
                <i class="glyphicon glyphicon-log-out"></i></a></li>
          {% else %}
            <li><a class="btn btn-default" href="{% url 'google_login' %}">sign in</a></li>
          {% endif %}
          </ul>
        </div>
      </div>
    {% endblock %}
    </nav>

    <div id="content" class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
      {% block content %}
        <!-- Main page content goes here -->
      {% endblock %}
    </div>

    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <form class="well" method="post" action="{% url 'account_logout' %}">
            <div class="modal-header">
              <h3>Are you sure you want to log out?</h3>
            </div>
            <div class="modal-body">
              {% csrf_token %}
            </div>
            <div class="modal-footer">
              <input class="btn btn-primary" type="submit" value="Log Out" />
              <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
          </form>
        </div>
      </div>
    </div>

  </div>

  <!-- js -->
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <script src="https://bootflat.github.io/bootflat/js/icheck.min.js"></script>
  <script src="{% static 'gradecalc/localforage.js' %}"></script>
</body>
</html>

templates/gradecalc/index.html
{% extends "gradecalc/base.html" %}
{% block title %}Grade Calculator{% endblock %}
{% block content %}
    <div id="courses" class="panel-group panel-group-lists collapse in">
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a href="#collapseCourseHome" data-parent="#courses"
                       data-toggle="collapse">Home</a>
                </h4>
            </div>
            <div id="collapseCourseHome" class="panel-collapse collapse in flex-container">
                <div class="panel-body">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing
                    elit. Donec a diam lectus. Sed sit amet ipsum mauris.
                    Maecenas congue ligula ac quam viverra nec consectetur
                    ante hendrerit. Donec et mollis dolor. Praesent et diam
                    eget libero egestas mattis sit amet vitae augue. Nam
                    tincidunt congue enim, ut porta lorem lacinia
                    consectetur. Donec ut libero sed arcu vehicula ultricies
                    a non tortor. Lorem ipsum dolor sit amet, consectetur
                    adipiscing elit. Aenean ut gravida lorem. Ut turpis
                    felis, pulvinar a semper sed, adipiscing id dolor.
                    Pellentesque auctor nisi id magna consequat sagittis.
                    Curabitur dapibus enim sit amet elit pharetra tincidunt
                    feugiat nisl imperdiet. Ut convallis libero in urna
                    ultrices accumsan. Donec sed odio eros. Donec viverra mi
                    quis quam pulvinar at malesuada arcu rhoncus. Cum sociis
                    natoque penatibus et magnis dis parturient montes,
                    nascetur ridiculus mus. In rutrum accumsan ultricies.
                    Mauris vitae nisi at sem facilisis semper ac in
                    est.</p>

                    <p>Vivamus fermentum semper porta. Nunc diam velit,
                    adipiscing ut tristique vitae, sagittis vel odio.
                    Maecenas convallis ullamcorper ultricies. Curabitur
                    ornare, ligula semper consectetur sagittis, nisi diam
                    iaculis velit, id fringilla sem nunc vel mi. Nam dictum,
                    odio nec pretium volutpat, arcu ante placerat erat, non
                    tristique elit urna et turpis. Quisque mi metus, ornare
                    sit amet fermentum et, tincidunt et orci. Fusce eget orci
                    a orci congue vestibulum. Ut dolor diam, elementum et
                    vestibulum eu, porttitor vel elit. Curabitur venenatis
                    pulvinar tellus gravida ornare. Sed et erat faucibus
                    nunc euismod ultricies ut id justo. Nullam cursus
                    suscipit nisi, et ultrices justo sodales nec. Fusce
                    venenatis facilisis lectus ac semper. Aliquam at massa
                    ipsum. Quisque bibendum purus convallis nulla ultrices
                    ultricies. Nullam aliquam, mi eu aliquam tincidunt,
                    purus velit laoreet tortor, viverra pretium nisi quam
                    vitae mi. Fusce vel volutpat elit. Nam sagittis nisi
                    dui.</p>
                </div>
            </div>
        </div>
        {% for course in courses %}
        <div class="panel">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="collapsed" href="#collapseCourse{{ course.course_id }}"
                       data-parent="#courses" data-toggle="collapse">{{ course.course_id }}: {{ course.name }}</a>
                </h4>
            </div>
            <div id="collapseCourse{{ course.course_id }}" class="panel-collapse collapse">
                <div class="panel-body">
                    {# Only PercentCourses have groups. #}
                    {% for group in course.group_set.all %}
                    <div class="flex-group">
                        {{ group.name }}: {{ group.percent }}%<br>
                        {% for assignment in group.percentassignment_set.all %}
                        <div class="flex-assignment flex-assignment-{{ forloop.counter }}">
                            <div class="col-xs-7">{{ assignment.name }}</div>
                        </div>
                        {% endfor %}
                        <div class="flex-new-assignment">
                            <div class="col-xs-8">
                                <input placeholder="Name" class="form-control"
                                       name="assignment_name"></input>
                            </div>
                            <div class="col-xs-3">
                                <input placeholder="Grade" type="number" class="form-control"
                                       min=0 step=1 name="grade"></input>
                            </div>
                            <div class="col-xs-1">
                                <input type=hidden value="{{ group.name }}" name=group></input>
                                <button class="btn">+</button>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {# Now do the PointsCourses. #}
                    {% if course.pointsassignment_set.all %}
                    <div class="flex-group">
                        {% for assignment in course.pointsassignment_set.all %}
                        <div class="flex-assignment flex-assignment-{{ forloop.counter }}">
                            <div class="col-xs-7">{{ assignment.name }}</div>
                            <div class="col-xs-2">{{ assignment.points }}</div>
                        </div>
                        {% endfor %}
                        <div class="flex-new-assignment">
                            <div class="col-xs-7">
                                <input placeholder="Name" class="form-control"
                                       name="assignment_name"></input>
                            </div>
                            <div class="col-xs-2">
                                <input placeholder="Points" type="number" class="form-control"
                                       min=0 step=1 name="points"></input>
                            </div>
                            <div class="col-xs-2">
                                <input placeholder="Grade" type="number" class="form-control"
                                       min=0 step=1 name="grade"></input>
                            </div>
                            <div class="col-xs-1">
                                <input type=hidden value="{{ course.course_id }}" name=course></input>
                                <button class="btn">+</button>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
{% endblock %}